#!/bin/bash

# vérification et récupération des arguments (<servername> <IP address>)
if [ -z $1 ];then
  echo
  read -p "Nom du serveur : " host
else
  host=$1
fi

if [ -z $2 ]; then
  echo
  read -p "Adresse IP : " IP
else
  IP=$2
fi

#

# Inscription de l'IP dans le script de post-install
sed -i "s/IP='.*'/IP='$IP'/" postinstall.sh

# création de l'instance avec association à Ext-Net
nova boot --key-name Desktop \
          --image "Ubuntu 16.04" \
          --flavor vps-ssd-1 \
          --nic net-id=8d3e91fd-c533-418f-8678-4252de201489 \
          --user-data postinstall.sh \
          --poll $host

# association à VLAN1
nova interface-attach --net-id f514b6f0-1556-44ac-b0a2-6f0babce821b --fixed-ip $IP $host

# mise à jour du fichier /etc/hosts
echo
echo "Mise à jour de /etc/hosts  et vlan1-hosts : "
echo

~/secretbox.cloud/hosts-update

echo
echo "En attente redémarrage serveur."
sleep 20
echo "Demande de redémarrage hard du serveur."
nova reboot --hard --poll $host

echo
exit 0

