#!/bin/bash

# vérification et récupération des arguments (<servername> <IP address>
if [ -z $1 ];then
  echo
  read -p "Nom du serveur : " host
else
  host=$1
fi

if [ -z $2 ]; then
  echo
  read -p "Adresse IP : " IP
else
  IP=$2
fi

# création de l'instance
nova boot --key-name Desktop --image "Ubuntu 16.04" --flavor vps-ssd-1 --nic net-name=Ext-Net --poll $host

# attachement au vRack
nova interface-attach --net-id 8ed23bf0-3ad3-4c29-9485-a821869d9ad4 --fixed-ip $IP $host

