#!/bin/bash

clear
echo "======================================================"
echo "          démarrage noeud de cluster galera           "
echo "======================================================"
echo

# Arrêt du noeud
sudo service mysql stop

# Démarrage du noeud
read -n1 -p "Démarrage en tant que premier node du cluster ? (y/n) " k
if [ $k = "y" ]; then
  sudo galera_new_cluster
else
  sudo service mysql start
fi

# affichage de la taille du cluster
echo -e "\nEntrer le mot de passe root mysql :"
mysql -u root -p -e "SHOW STATUS LIKE 'wsrep_cluster_size';"

echo
exit 0


