#!/bin/bash

echo
echo "======================================================"
echo "           initialisation du cluster galera           "
echo "======================================================"
echo

# mise à jour de /etc/hosts
echo -e "\n========> mise à jour de la liste des serveurs ...\n"
./hosts-update

# on rapatrie le fichier debian.cnf du serveur gdb-g1
echo -e "\n========> Récupération de debian.cnf sur 'gdb-g1' ...\n"
scp gdb-g1:/etc/mysql/debian.cnf ./debian.cnf

if [ $? -ne 0 ]; then
  echo -e "\nProblème lors de la récupération de debian.cnf => Abandon.\n"
  exit 1
fi

# on récupère dans les lignes de /etc/hosts tous les hôtes en 'gdb'
echo -e "\n========> Ecriture de debian.cnf sur les autres hôtes du cluster ...\n"
cat /etc/hosts | grep gdb > lines.txt

# on construit la liste des adresses IP
IPlist=""
while read line; do
  IP=$(echo $line | sed "s/^\([0-9]*.[0-9]*.[0-9]*.[0-9]*\).*$/\1/")
  IPlist="${IPlist},$IP"
done < lines.txt
IPlist=$(echo $IPlist | sed "s/^,//")

while read line; do
  host=$(echo $line | sed "s/^.*\s\(.*\)\.secretbox.*$/\1/")
  IP=$(echo $line | sed "s/^\([0-9]*.[0-9]*.[0-9]*.[0-9]*\).*$/\1/")
  if [ $host != 'gdb-g1' ]; then
    echo "Ecriture sur $host ($IP)"
    scp ./debian.cnf $host:~/debian.cnf
    ssh stef@$host 'sudo mv ~/debian.cnf /etc/mysql/debian.cnf'
    ssh stef@$host 'sudo chown root:root /etc/mysql/debian.cnf'
    cmd="\"s/gcomm:\/\/.*\\\"/gcomm:\/\/$IPlist\\\"/\""
    ssh stef@$host "sudo sed -i $cmd /etc/mysql/conf.d/galera.cnf"
    ssh stef@$host 'sudo service mysql stop'
  fi
done < lines.txt

exit 2

# Démarrage du premier noeud (gdb-g1)
echo -e "\n========> Démarrage du premier noeud du cluster ...\n"
ssh stef@gdb-g1 'sudo galera_new_cluster'

# Démarrage des autres noeuds
echo -e "\n========> Démarrage des autres noeuds du cluster ...\n"
cat /etc/hosts | grep gdb > lines.txt
while read line; do
  host=$(echo $line | sed "s/^.*\s\(.*\)\.secretbox.*$/\1/")
  if [ $host != 'gdb-g1' ]; then
    echo "Démarrage de $host"
    ssh stef@$host 'sudo service mysql start'
  fi
done < lines.txt

# Nettoyage
sudo rm lines.txt
sudo rm debian.cnf

echo
exit 0


