#!/bin/bash

clear
echo "======================================================="
echo "               Installation serveur DB                 "
echo "======================================================="
echo

echo -e "\n========> Mise à jour du système ...\n\n"
sudo apt -y update
echo
sudo apt -y upgrade

echo -e "\n\n========> Installation MariaDB ...\n\n"
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu xenial main'
sudo apt-get update
sudo apt-get -y install mariadb-server

echo -e "\n\n========> Installation Rsync ...\n\n"
sudo apt -y install rsync

echo -e "\n========> Création du fichier de configuration ...\n"
echo "[mysqld]"						| sudo tee /etc/mysql/conf.d/galera.cnf
echo "query_cache_size=0"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "binlog_format=ROW"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "default-storage-engine=innodb"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "innodb_autoinc_lock_mode=2"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "bind-address=0.0.0.0"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Provider Configuration"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_on=ON"					| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_provider=/usr/lib/galera/libgalera_smm.so"	| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Cluster Configuration"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo 'wsrep_cluster_name="db_cluster"'			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo 'wsrep_cluster_address="gcomm://10.1.3.1,10.1.3.2"' | sudo tee -a /etc/mysql/conf.d/galera.cnf
echo '#                      #########################\n' | sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Synchronization Configuration"		| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_sst_method=rsync"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Node Configuration"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
localIP=$(ip addr | grep -o "inet 10\.[0-9]*\.[0-9]*\.[0-9]*" | sed "s/inet //")
echo "wsrep_node_address=\"$localIP\""			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_node_name=\"$(hostname)\""			| sudo tee -a /etc/mysql/conf.d/galera.cnf

sudo nano /etc/mysql/conf.d/galera.cnf

sudo sed -i "s/bind-address.*127.0.0.1/#bind-address = 127.0.0.1" /etc/mysql/my.cnf

echo -e "\n========> Arrêt du serveur mysql ...\n"
sudo service mysql stop

echo -e "\n======================================================================="
echo -e "\nIl faut maintenant copier le contenu de /etc/mysql/debian.cnf vers"
echo -e "chacun des autres noeuds du cluster."
echo -e "=======================================================================\n"
sudo cat /etc/mysql/debian.cnf

echo
exit 0

