#!/bin/bash

clear
echo "======================================================="
echo "               Installation serveur DB                 "
echo "======================================================="
echo

echo -e "\n========> Mise à jour du système ...\n\n"
sudo apt -y update
echo
sudo apt -y upgrade
echo
sudo apt -y install software-properties-common

echo -e "\n\n========> Installation MariaDB + Galera ...\n\n"
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
sudo add-apt-repository 'deb http://mirror.jmu.edu/pub/mariadb/repo/10.1/ubuntu xenial main'
sudo apt -y update
sudo apt -y install mariadb-client mariadb-galera-server galera

echo -e "\n\n========> Installation Rsync ...\n\n"
sudo apt -y install rsync

echo -e "\n========> Désactivation AppArmor pour mysql ...\n"
sudo ln -s /etc/apparmor.d/usr /etc/apparmor.d/disable/.sbin.mysqld
sudo service apparmor restart

echo -e "\n========> Création d'un fichier swap ...\n"
sudo fallocate -l 1G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo "/swapfile none swap defaults 0 0" | sudo tee -a /etc/fstab

echo -e "\n========> Configuration du serveur MySql ...\n"
sudo sed -i "s/bind-address.*127.0.0.1/bind-address=0.0.0.0/" /etc/mysql/my.cnf

echo -e "\n========> Création du fichier de configuration du cluster ...\n"
echo "[mysqld]"						| sudo tee /etc/mysql/conf.d/galera.cnf
echo "binlog_format=ROW"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "default-storage-engine=innodb"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "innodb_autoinc_lock_mode=2"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "bind-address=0.0.0.0"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Provider Configuration"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_on=ON"					| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_provider=/usr/lib/galera/libgalera_smm.so"	| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Cluster Configuration"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo 'wsrep_cluster_name="db_cluster"'			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo 'wsrep_cluster_address="gcomm://10.1.3.1"'		| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Synchronization Configuration"		| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_sst_method=rsync"				| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo							| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "# Galera Node Configuration"			| sudo tee -a /etc/mysql/conf.d/galera.cnf
localIP=$(ip addr | grep -o "inet 10\.[0-9]*\.[0-9]*\.[0-9]*" | sed "s/inet //")
echo "wsrep_node_address=\"$localIP\""			| sudo tee -a /etc/mysql/conf.d/galera.cnf
echo "wsrep_node_name=\"$(hostname)\""			| sudo tee -a /etc/mysql/conf.d/galera.cnf



echo -e "\n========> Arrêt du serveur mysql ...\n"
sudo service mysql stop

echo
exit 0

