#!/bin/bash

if [ -z $1 ]; then
  read -p "Nom du serveur : " host
else
  host=$1
fi

echo
echo "Suppression du serveur $host."

nova delete $host

ssh-keygen -R $host

echo
echo "Mise à jour des fichiers hosts :"
echo
~/secretbox.cloud/hosts-update

echo
exit 0
