#!/bin/bash

clear
echo "=========================================================="
echo "           Installation HA-Proxy pour cluster DB          "
echo "=========================================================="
echo

echo -e "========> Mise à jour du système ...\n"
sudo apt -y update
echo
sudo apt -y upgrade

echo -e "\n========> Installation de Mariadb client ...\n"
sudo apt -y install mariadb-client

echo -e "\n========> Installation HA Proxy ... \n"
sudo apt -y install haproxy

echo -e "\n========> Configuration de HA Proxy ...\n"
echo -e "\nENABLED=1\n" | sudo tee -a /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
echo -e "global" | sudo tee /etc/haproxy/haproxy.cfg
echo -e "    log 127.0.0.1 local0" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    log 127.0.0.1 local1 notice" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    maxconn 1024" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    user haproxy" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    group haproxy" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    daemon" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "defaults" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    log global" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    mode http" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    option tcplog" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    option dontlognull" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    retries 3" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    option redispatch" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    maxconn 1024" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    timeout connect 5000ms" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    timeout client 50000ms" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    timeout server 50000ms\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "listen galera_cluster" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    bind 0.0.0.0:3306" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    mode tcp" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    option tcpka" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    option mysql-check user haproxy_check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    server db-g1 10.1.3.1:3306 check weight 1" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    server db-s1 10.2.3.1:3306 check weight 1" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "    server db-b1 10.3.3.1:3306 check weight 1\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "listen stats"
echo -e "    bind 0.0.0.0:80"
echo -e "    stats enable"
echo -e "    stats hide-version"
echo -e "    stats refresh 10s"
echo -e "    stats show-node"
echo -e "    stats auth stef:lolomila"
echo -e "    stats uri /\n"

echo -e "\n========> Démarrage de HA Proxy ...\n"
sudo service haproxy start
sudo service haproxy reload
sudo netstat -plantu | grep 3306

echo -e "\n========> Test de connexion MySql ...\n"
echo -e "\nTEST 1 :"
mysql -u haproxy_check -p -h 127.0.0.1 -e "show variables like 'wsrep_node_name';"




