#!/bin/bash

# installation de heartbeat
sudo apt -y install heartbeat

# ajout des nodes dans /etc/hosts
echo "10.1.2.101 lbdb-g1" | sudo tee -a /etc/hosts
echo "10.3.2.101 lbdb-b1" | sudo tee -a /etc/hosts

# configuration générale de heartbeat
echo "logfile /var/log/ha-log" | sudo tee /etc/ha.d/ha.cf
echo "logfacility local0" | sudo tee -a /etc/ha.d/ha.cf
echo "keepalive 2" | sudo tee -a /etc/ha.d/ha.cf
echo "deadtime 10" | sudo tee -a /etc/ha.d/ha.cf
echo "bcast eth1" | sudo tee -a /etc/ha.d/ha.cf
echo "node lbdb-g1 lbdb-b1" | sudo tee -a /etc/ha.d/ha.cf
echo "auto_failback on" | sudo tee -a /etc/ha.d/ha.cf
echo "respawn hacluster /usr/lib/heartbeat/ipfail" | sudo tee -a /etc/ha.d/ha.cf
echo "apiauth ipfail gid=haclient uid=hacluster" | sudo tee -a /etc/ha.d/ha.cf

# configuration des ressources de heartbeat
echo "lbdb-g1 IPaddr::10.1.2.100/8/eth1 haproxy" | sudo tee /etc/ha.d/haresources

# configuration de la clé partagée heartbeat
echo "auth 3" | sudo tee /etc/ha.d/authkeys
echo "3 md5 l0l0m1l4" | sudo tee -a /etc/ha.d/authkeys
sudo chmod 600 /etc/ha.d/authkeys

# désactivation démarrage automatique de haproxy
sudo service haproxy stop
sudo systemctl disable haproxy

# démarrage de heartbeat
sudo service heartbeat restart

