#!/bin/bash

# =======================================================================
#          Mise à jour de la liste des serveurs secretbox.cloud
# =======================================================================

export OS_REGION_NAME=GRA1
nova list | grep "ACTIVE" > tmp.list

export OS_REGION_NAME=SBG1
nova list | grep "ACTIVE" >> tmp.list

export OS_REGION_NAME=BHS1
nova list | grep "ACTIVE" >> tmp.list

export OS_REGION_NAME=GRA1

sudo sed -i '/.secretbox.cloud/d' /etc/hosts
> vlan1-hosts

while read ligne
do
  host=$(echo $ligne | sed 's/\s*//g' | cut -d'|' -f3)
  network=$(echo $ligne | sed 's/\s*//g' | cut -d'|' -f7)
  extIP=$(echo $network | grep -o 'Ext\-Net=[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*' | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*')
  if [ -z $extIP ]; then
    extIP=$(echo $network | grep -o 'Ext\-Net=.*[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*;' | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*')
  fi
  intIP=$(echo $network | grep -o 'secretbox10=[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*' | grep -o '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*')
  echo -e "$extIP\t\t$host.secretbox.cloud\t\t\t$host" | sudo tee -a /etc/hosts >> /dev/null
  echo -e "$intIP\t\t$host.secretbox.cloud\t\t\t$host" >> vlan1-hosts
done < tmp.list

rm tmp.list

echo
echo "======== /etc/hosts ========"
cat /etc/hosts

echo
echo "======== vlan1-hosts ========"
cat vlan1-hosts

echo
exit 0


