#!/bin/bash

sudo apt -y update

sudo apt -y install nfs-common

sudo mkdir /share
sudo sed -i "/\/share/d" /etc/fstab
echo -e "10.0.0.2:/share\t\t/share\t\tnfs\tauto,nofail,noatime,nolock,intr,tcp,actimeo=1800\t0 0" | sudo tee -a /etc/fstab

sudo mount -a

exit 0

